## car price 

In [3]:
import pandas as pd

In [4]:
df=pd.read_csv('CarPrice_Assignment.csv')

In [5]:
pd.set_option('display.max_columns', None)

In [6]:
df.head(26)

car_ID  symboling                   CarName fueltype aspiration  \
0        1          3        alfa-romero giulia      gas        std   
1        2          3       alfa-romero stelvio      gas        std   
2        3          1  alfa-romero Quadrifoglio      gas        std   
3        4          2               audi 100 ls      gas        std   
4        5          2                audi 100ls      gas        std   
5        6          2                  audi fox      gas        std   
6        7          1                audi 100ls      gas        std   
7        8          1                 audi 5000      gas        std   
8        9          1                 audi 4000      gas      turbo   
9       10          0       audi 5000s (diesel)      gas      turbo   
10      11          2                  bmw 320i      gas        std   
11      12          0                  bmw 320i      gas        std   
12      13          0                    bmw x1      gas        std   
13      14          0                    bmw x3      gas        std   
14      15          1                    bmw z4      gas        std   
15      16          0                    bmw x4      gas        std   
16      17          0                    bmw x5      gas        std   
17      18          0                    bmw x3      gas        std   
18      19          2          chevrolet impala      gas        std   
19      20          1     chevrolet monte carlo      gas        std   
20      21          0       chevrolet vega 2300      gas        std   
21      22          1             dodge rampage      gas        std   
22      23          1       dodge challenger se      gas        std   
23      24          1                dodge d200      gas      turbo   
24      25          1         dodge monaco (sw)      gas        std   
25      26          1        dodge colt hardtop      gas        std   

   doornumber      carbody drivewheel enginelocation  wheelbase  carlength  \
0         two  convertible        rwd          front       88.6      168.8   
1         two  convertible        rwd          front       88.6      168.8   
2         two    hatchback        rwd          front       94.5      171.2   
3        four        sedan        fwd          front       99.8      176.6   
4        four        sedan        4wd          front       99.4      176.6   
5         two        sedan        fwd          front       99.8      177.3   
6        four        sedan        fwd          front      105.8      192.7   
7        four        wagon        fwd          front      105.8      192.7   
8        four        sedan        fwd          front      105.8      192.7   
9         two    hatchback        4wd          front       99.5      178.2   
10        two        sedan        rwd          front      101.2      176.8   
11       four        sedan        rwd          front      101.2      176.8   
12        two        sedan        rwd          front      101.2      176.8   
13       four        sedan        rwd          front      101.2      176.8   
14       four        sedan        rwd          front      103.5      189.0   
15       four        sedan        rwd          front      103.5      189.0   
16        two        sedan        rwd          front      103.5      193.8   
17       four        sedan        rwd          front      110.0      197.0   
18        two    hatchback        fwd          front       88.4      141.1   
19        two    hatchback        fwd          front       94.5      155.9   
20       four        sedan        fwd          front       94.5      158.8   
21        two    hatchback        fwd          front       93.7      157.3   
22        two    hatchback        fwd          front       93.7      157.3   
23        two    hatchback        fwd          front       93.7      157.3   
24       four    hatchback        fwd          front       93.7      157.3   
25       four        sedan        fwd          front      

In [7]:
print(df)

     car_ID  symboling                   CarName fueltype aspiration  \
0         1          3        alfa-romero giulia      gas        std   
1         2          3       alfa-romero stelvio      gas        std   
2         3          1  alfa-romero Quadrifoglio      gas        std   
3         4          2               audi 100 ls      gas        std   
4         5          2                audi 100ls      gas        std   
..      ...        ...                       ...      ...        ...   
200     201         -1           volvo 145e (sw)      gas        std   
201     202         -1               volvo 144ea      gas      turbo   
202     203         -1               volvo 244dl      gas        std   
203     204         -1                 volvo 246   diesel      turbo   
204     205         -1               volvo 264gl      gas      turbo   

    doornumber      carbody drivewheel enginelocation  wheelbase  carlength  \
0          two  convertible        rwd          front   

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   car_ID            205 non-null    int64  
 1   symboling         205 non-null    int64  
 2   CarName           205 non-null    object 
 3   fueltype          205 non-null    object 
 4   aspiration        205 non-null    object 
 5   doornumber        205 non-null    object 
 6   carbody           205 non-null    object 
 7   drivewheel        205 non-null    object 
 8   enginelocation    205 non-null    object 
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64  
 14  enginetype        205 non-null    object 
 15  cylindernumber    205 non-null    object 
 16  enginesize        205 non-null    int64  
 1

In [9]:
# df=pd.read_excel('Data Dictionary - carprices.xlsx')

In [10]:
df.tail()

car_ID  symboling          CarName fueltype aspiration doornumber  \
200     201         -1  volvo 145e (sw)      gas        std       four   
201     202         -1      volvo 144ea      gas      turbo       four   
202     203         -1      volvo 244dl      gas        std       four   
203     204         -1        volvo 246   diesel      turbo       four   
204     205         -1      volvo 264gl      gas      turbo       four   

    carbody drivewheel enginelocation  wheelbase  carlength  carwidth  \
200   sedan        rwd          front      109.1      188.8      68.9   
201   sedan        rwd          front      109.1      188.8      68.8   
202   sedan        rwd          front      109.1      188.8      68.9   
203   sedan        rwd          front      109.1      188.8      68.9   
204   sedan        rwd          front      109.1      188.8      68.9   

     carheight  curbweight enginetype cylindernumber  enginesize fuelsystem  \
200       55.5        2952        ohc           four         141       mpfi   
201       55.5        3049        ohc           four         141       mpfi   
202       55.5        3012       ohcv            six         173       mpfi   
203       55.5        3217        ohc            six         145        idi   
204       55.5        3062        ohc           four         141       mpfi   

     boreratio  stroke  compressionratio  horsepower  peakrpm  citympg  \
200       3.78    3.15               9.5         114     5400       23   
201       3.78    3.15               8.7         160     5300       19   
202       3.58    2.87               8.8         134     5500       18   
203       3.01    3.40              23.0         106     4800       26   
204       3.78    3.15               9.5         114     5400       19   

     highwaympg    price  
200          28  16845.0  
201          25  19045.0  
202          23  21485.0  
203          27  22470.0  
204          25  22625.0

In [11]:
car=df.copy()
car.head()

car_ID  symboling                   CarName fueltype aspiration doornumber  \
0       1          3        alfa-romero giulia      gas        std        two   
1       2          3       alfa-romero stelvio      gas        std        two   
2       3          1  alfa-romero Quadrifoglio      gas        std        two   
3       4          2               audi 100 ls      gas        std       four   
4       5          2                audi 100ls      gas        std       four   

       carbody drivewheel enginelocation  wheelbase  carlength  carwidth  \
0  convertible        rwd          front       88.6      168.8      64.1   
1  convertible        rwd          front       88.6      168.8      64.1   
2    hatchback        rwd          front       94.5      171.2      65.5   
3        sedan        fwd          front       99.8      176.6      66.2   
4        sedan        4wd          front       99.4      176.6      66.4   

   carheight  curbweight enginetype cylindernumber  enginesize fuelsystem  \
0       48.8        2548       dohc           four         130       mpfi   
1       48.8        2548       dohc           four         130       mpfi   
2       52.4        2823       ohcv            six         152       mpfi   
3       54.3        2337        ohc           four         109       mpfi   
4       54.3        2824        ohc           five         136       mpfi   

   boreratio  stroke  compressionratio  horsepower  peakrpm  citympg  \
0       3.47    2.68               9.0         111     5000       21   
1       3.47    2.68               9.0         111     5000       21   
2       2.68    3.47               9.0         154     5000       19   
3       3.19    3.40              10.0         102     5500       24   
4       3.19    3.40               8.0         115     5500       18   

   highwaympg    price  
0          27  13495.0  
1          27  16500.0  
2          26  16500.0  
3          30  13950.0  
4          22  17450.0

In [12]:
car.describe()

car_ID   symboling   wheelbase   carlength    carwidth   carheight  \
count  205.000000  205.000000  205.000000  205.000000  205.000000  205.000000   
mean   103.000000    0.834146   98.756585  174.049268   65.907805   53.724878   
std     59.322565    1.245307    6.021776   12.337289    2.145204    2.443522   
min      1.000000   -2.000000   86.600000  141.100000   60.300000   47.800000   
25%     52.000000    0.000000   94.500000  166.300000   64.100000   52.000000   
50%    103.000000    1.000000   97.000000  173.200000   65.500000   54.100000   
75%    154.000000    2.000000  102.400000  183.100000   66.900000   55.500000   
max    205.000000    3.000000  120.900000  208.100000   72.300000   59.800000   

        curbweight  enginesize   boreratio      stroke  compressionratio  \
count   205.000000  205.000000  205.000000  205.000000        205.000000   
mean   2555.565854  126.907317    3.329756    3.255415         10.142537   
std     520.680204   41.642693    0.270844    0.313597          3.972040   
min    1488.000000   61.000000    2.540000    2.070000          7.000000   
25%    2145.000000   97.000000    3.150000    3.110000          8.600000   
50%    2414.000000  120.000000    3.310000    3.290000          9.000000   
75%    2935.000000  141.000000    3.580000    3.410000          9.400000   
max    4066.000000  326.000000    3.940000    4.170000         23.000000   

       horsepower      peakrpm     citympg  highwaympg         price  
count  205.000000   205.000000  205.000000  205.000000    205.000000  
mean   104.117073  5125.121951   25.219512   30.751220  13276.710571  
std     39.544167   476.985643    6.542142    6.886443   7988.852332  
min     48.000000  4150.000000   13.000000   16.000000   5118.000000  
25%     70.000000  4800.000000   19.000000   25.000000   7788.000000  
50%     95.000000  5200.000000   24.000000   30.000000  10295.000000  
75%    116.000000  5500.000000   30.000000   34.000000  16503.000000  
max    288.000000  6600.000000   49.000000   54.000000  45400.000000

In [13]:
car.shape

(205, 26)

In [14]:
car.isnull().sum()

car_ID              0
symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

In [15]:
car['doornumber'].unique()

array(['two', 'four'], dtype=object)

In [16]:
car['doornumber'].replace(['two','four'],[2,4],inplace=True)

In [17]:
car['doornumber'].unique()

array([2, 4])

In [18]:
car['cylindernumber'].unique()

array(['four', 'six', 'five', 'three', 'twelve', 'two', 'eight'],
      dtype=object)

In [19]:
car['cylindernumber'].replace(['four','six','five','three','twelve','two','eight'],[4,6,5,3,12,2,8],inplace=True)

In [20]:
car['cylindernumber'].unique()

array([ 4,  6,  5,  3, 12,  2,  8])

In [21]:
car.head()

car_ID  symboling                   CarName fueltype aspiration  \
0       1          3        alfa-romero giulia      gas        std   
1       2          3       alfa-romero stelvio      gas        std   
2       3          1  alfa-romero Quadrifoglio      gas        std   
3       4          2               audi 100 ls      gas        std   
4       5          2                audi 100ls      gas        std   

   doornumber      carbody drivewheel enginelocation  wheelbase  carlength  \
0           2  convertible        rwd          front       88.6      168.8   
1           2  convertible        rwd          front       88.6      168.8   
2           2    hatchback        rwd          front       94.5      171.2   
3           4        sedan        fwd          front       99.8      176.6   
4           4        sedan        4wd          front       99.4      176.6   

   carwidth  carheight  curbweight enginetype  cylindernumber  enginesize  \
0      64.1       48.8        2548       dohc               4         130   
1      64.1       48.8        2548       dohc               4         130   
2      65.5       52.4        2823       ohcv               6         152   
3      66.2       54.3        2337        ohc               4         109   
4      66.4       54.3        2824        ohc               5         136   

  fuelsystem  boreratio  stroke  compressionratio  horsepower  peakrpm  \
0       mpfi       3.47    2.68               9.0         111     5000   
1       mpfi       3.47    2.68               9.0         111     5000   
2       mpfi       2.68    3.47               9.0         154     5000   
3       mpfi       3.19    3.40              10.0         102     5500   
4       mpfi       3.19    3.40               8.0         115     5500   

   citympg  highwaympg    price  
0       21          27  13495.0  
1       21          27  16500.0  
2       19          26  16500.0  
3       24          30  13950.0  
4       18          22  17450.0

In [22]:
car['fueltype'].unique()

array(['gas', 'diesel'], dtype=object)

In [23]:
dummies=pd.get_dummies(car['fueltype'],prefix='fuel_type')
dummies

fuel_type_diesel  fuel_type_gas
0                   0              1
1                   0              1
2                   0              1
3                   0              1
4                   0              1
..                ...            ...
200                 0              1
201                 0              1
202                 0              1
203                 1              0
204                 0              1

[205 rows x 2 columns]

In [24]:
car=pd.concat((car,dummies),axis=1)
car.head()

car_ID  symboling                   CarName fueltype aspiration  \
0       1          3        alfa-romero giulia      gas        std   
1       2          3       alfa-romero stelvio      gas        std   
2       3          1  alfa-romero Quadrifoglio      gas        std   
3       4          2               audi 100 ls      gas        std   
4       5          2                audi 100ls      gas        std   

   doornumber      carbody drivewheel enginelocation  wheelbase  carlength  \
0           2  convertible        rwd          front       88.6      168.8   
1           2  convertible        rwd          front       88.6      168.8   
2           2    hatchback        rwd          front       94.5      171.2   
3           4        sedan        fwd          front       99.8      176.6   
4           4        sedan        4wd          front       99.4      176.6   

   carwidth  carheight  curbweight enginetype  cylindernumber  enginesize  \
0      64.1       48.8        2548       dohc               4         130   
1      64.1       48.8        2548       dohc               4         130   
2      65.5       52.4        2823       ohcv               6         152   
3      66.2       54.3        2337        ohc               4         109   
4      66.4       54.3        2824        ohc               5         136   

  fuelsystem  boreratio  stroke  compressionratio  horsepower  peakrpm  \
0       mpfi       3.47    2.68               9.0         111     5000   
1       mpfi       3.47    2.68               9.0         111     5000   
2       mpfi       2.68    3.47               9.0         154     5000   
3       mpfi       3.19    3.40              10.0         102     5500   
4       mpfi       3.19    3.40               8.0         115     5500   

   citympg  highwaympg    price  fuel_type_diesel  fuel_type_gas  
0       21          27  13495.0                 0              1  
1       21          27  16500.0                 0              1  
2       19          26  16500.0                 0              1  
3       24          30  13950.0                 0              1  
4       18          22  17450.0                 0              1

In [25]:
car.drop('fuel_type_gas',axis=1,inplace=True)

In [26]:
car.head()

car_ID  symboling                   CarName fueltype aspiration  \
0       1          3        alfa-romero giulia      gas        std   
1       2          3       alfa-romero stelvio      gas        std   
2       3          1  alfa-romero Quadrifoglio      gas        std   
3       4          2               audi 100 ls      gas        std   
4       5          2                audi 100ls      gas        std   

   doornumber      carbody drivewheel enginelocation  wheelbase  carlength  \
0           2  convertible        rwd          front       88.6      168.8   
1           2  convertible        rwd          front       88.6      168.8   
2           2    hatchback        rwd          front       94.5      171.2   
3           4        sedan        fwd          front       99.8      176.6   
4           4        sedan        4wd          front       99.4      176.6   

   carwidth  carheight  curbweight enginetype  cylindernumber  enginesize  \
0      64.1       48.8        2548       dohc               4         130   
1      64.1       48.8        2548       dohc               4         130   
2      65.5       52.4        2823       ohcv               6         152   
3      66.2       54.3        2337        ohc               4         109   
4      66.4       54.3        2824        ohc               5         136   

  fuelsystem  boreratio  stroke  compressionratio  horsepower  peakrpm  \
0       mpfi       3.47    2.68               9.0         111     5000   
1       mpfi       3.47    2.68               9.0         111     5000   
2       mpfi       2.68    3.47               9.0         154     5000   
3       mpfi       3.19    3.40              10.0         102     5500   
4       mpfi       3.19    3.40               8.0         115     5500   

   citympg  highwaympg    price  fuel_type_diesel  
0       21          27  13495.0                 0  
1       21          27  16500.0                 0  
2       19          26  16500.0                 0  
3       24          30  13950.0                 0  
4       18          22  17450.0                 0

In [27]:
car['aspiration'].unique()

array(['std', 'turbo'], dtype=object)

In [28]:
dummies2=pd.get_dummies(car['aspiration'],prefix='aspiration')

In [30]:
car=pd.concat((car,dummies2),axis=1)
car.head()

car_ID  symboling                   CarName fueltype aspiration  \
0       1          3        alfa-romero giulia      gas        std   
1       2          3       alfa-romero stelvio      gas        std   
2       3          1  alfa-romero Quadrifoglio      gas        std   
3       4          2               audi 100 ls      gas        std   
4       5          2                audi 100ls      gas        std   

   doornumber      carbody drivewheel enginelocation  wheelbase  carlength  \
0           2  convertible        rwd          front       88.6      168.8   
1           2  convertible        rwd          front       88.6      168.8   
2           2    hatchback        rwd          front       94.5      171.2   
3           4        sedan        fwd          front       99.8      176.6   
4           4        sedan        4wd          front       99.4      176.6   

   carwidth  carheight  curbweight enginetype  cylindernumber  enginesize  \
0      64.1       48.8        2548       dohc               4         130   
1      64.1       48.8        2548       dohc               4         130   
2      65.5       52.4        2823       ohcv               6         152   
3      66.2       54.3        2337        ohc               4         109   
4      66.4       54.3        2824        ohc               5         136   

  fuelsystem  boreratio  stroke  compressionratio  horsepower  peakrpm  \
0       mpfi       3.47    2.68               9.0         111     5000   
1       mpfi       3.47    2.68               9.0         111     5000   
2       mpfi       2.68    3.47               9.0         154     5000   
3       mpfi       3.19    3.40              10.0         102     5500   
4       mpfi       3.19    3.40               8.0         115     5500   

   citympg  highwaympg    price  fuel_type_diesel  aspiration_std  \
0       21          27  13495.0                 0               1   
1       21          27  16500.0                 0               1   
2       19          26  16500.0                 0               1   
3       24          30  13950.0                 0               1   
4       18          22  17450.0                 0               1   

   aspiration_turbo  
0                 0  
1                 0  
2                 0  
3                 0  
4                 0

In [31]:
car.drop('aspiration_turbo',axis=1,inplace=True)

In [32]:
car.head()

car_ID  symboling                   CarName fueltype aspiration  \
0       1          3        alfa-romero giulia      gas        std   
1       2          3       alfa-romero stelvio      gas        std   
2       3          1  alfa-romero Quadrifoglio      gas        std   
3       4          2               audi 100 ls      gas        std   
4       5          2                audi 100ls      gas        std   

   doornumber      carbody drivewheel enginelocation  wheelbase  carlength  \
0           2  convertible        rwd          front       88.6      168.8   
1           2  convertible        rwd          front       88.6      168.8   
2           2    hatchback        rwd          front       94.5      171.2   
3           4        sedan        fwd          front       99.8      176.6   
4           4        sedan        4wd          front       99.4      176.6   

   carwidth  carheight  curbweight enginetype  cylindernumber  enginesize  \
0      64.1       48.8        2548       dohc               4         130   
1      64.1       48.8        2548       dohc               4         130   
2      65.5       52.4        2823       ohcv               6         152   
3      66.2       54.3        2337        ohc               4         109   
4      66.4       54.3        2824        ohc               5         136   

  fuelsystem  boreratio  stroke  compressionratio  horsepower  peakrpm  \
0       mpfi       3.47    2.68               9.0         111     5000   
1       mpfi       3.47    2.68               9.0         111     5000   
2       mpfi       2.68    3.47               9.0         154     5000   
3       mpfi       3.19    3.40              10.0         102     5500   
4       mpfi       3.19    3.40               8.0         115     5500   

   citympg  highwaympg    price  fuel_type_diesel  aspiration_std  
0       21          27  13495.0                 0               1  
1       21          27  16500.0                 0               1  
2       19          26  16500.0                 0               1  
3       24          30  13950.0                 0               1  
4       18          22  17450.0                 0               1

In [33]:
car.dtypes

car_ID                int64
symboling             int64
CarName              object
fueltype             object
aspiration           object
doornumber            int64
carbody              object
drivewheel           object
enginelocation       object
wheelbase           float64
carlength           float64
carwidth            float64
carheight           float64
curbweight            int64
enginetype           object
cylindernumber        int64
enginesize            int64
fuelsystem           object
boreratio           float64
stroke              float64
compressionratio    float64
horsepower            int64
peakrpm               int64
citympg               int64
highwaympg            int64
price               float64
fuel_type_diesel      uint8
aspiration_std        uint8
dtype: object

In [34]:
num_cols = car.select_dtypes(exclude = 'object')
cat_cols = car.select_dtypes(include = 'object')

In [49]:
num_cols.drop('aspiration_std',axis=1,inplace=True)

In [50]:
num_cols.head()

car_ID  symboling  doornumber  wheelbase  carlength  carwidth  carheight  \
0       1          3           2       88.6      168.8      64.1       48.8   
1       2          3           2       88.6      168.8      64.1       48.8   
2       3          1           2       94.5      171.2      65.5       52.4   
3       4          2           4       99.8      176.6      66.2       54.3   
4       5          2           4       99.4      176.6      66.4       54.3   

   curbweight  cylindernumber  enginesize  boreratio  stroke  \
0        2548               4         130       3.47    2.68   
1        2548               4         130       3.47    2.68   
2        2823               6         152       2.68    3.47   
3        2337               4         109       3.19    3.40   
4        2824               5         136       3.19    3.40   

   compressionratio  horsepower  peakrpm  citympg  highwaympg    price  
0               9.0         111     5000       21          27  13495.0  
1               9.0         111     5000       21          27  16500.0  
2               9.0         154     5000       19          26  16500.0  
3              10.0         102     5500       24          30  13950.0  
4               8.0         115     5500       18          22  17450.0

In [51]:
X = num_cols.iloc[:, :-1].values
y = num_cols.iloc[:, -1].values

In [52]:
print(y)

[13495.    16500.    16500.    13950.    17450.    15250.    17710.
 18920.    23875.    17859.167 16430.    16925.    20970.    21105.
 24565.    30760.    41315.    36880.     5151.     6295.     6575.
  5572.     6377.     7957.     6229.     6692.     7609.     8558.
  8921.    12964.     6479.     6855.     5399.     6529.     7129.
  7295.     7295.     7895.     9095.     8845.    10295.    12945.
 10345.     6785.     8916.5    8916.5   11048.    32250.    35550.
 36000.     5195.     6095.     6795.     6695.     7395.    10945.
 11845.    13645.    15645.     8845.     8495.    10595.    10245.
 10795.    11245.    18280.    18344.    25552.    28248.    28176.
 31600.    34184.    35056.    40960.    45400.    16503.     5389.
  6189.     6669.     7689.     9959.     8499.    12629.    14869.
 14489.     6989.     8189.     9279.     9279.     5499.     7099.
  6649.     6849.     7349.     7299.     7799.     7499.     7999.
  8249.     8949.     9549.    13499.    14399. 

In [53]:
print(X)

[[ 1.00e+00  3.00e+00  2.00e+00 ...  5.00e+03  2.10e+01  2.70e+01]
 [ 2.00e+00  3.00e+00  2.00e+00 ...  5.00e+03  2.10e+01  2.70e+01]
 [ 3.00e+00  1.00e+00  2.00e+00 ...  5.00e+03  1.90e+01  2.60e+01]
 ...
 [ 2.03e+02 -1.00e+00  4.00e+00 ...  5.50e+03  1.80e+01  2.30e+01]
 [ 2.04e+02 -1.00e+00  4.00e+00 ...  4.80e+03  2.60e+01  2.70e+01]
 [ 2.05e+02 -1.00e+00  4.00e+00 ...  5.40e+03  1.90e+01  2.50e+01]]


In [55]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [57]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(X_train, y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

In [58]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[ 5974.7   6795.  ]
 [17137.   15750.  ]
 [15326.12 15250.  ]
 [ 6125.6   5151.  ]
 [ 9905.8   9995.  ]
 [16712.4  11199.  ]
 [ 5890.4   5389.  ]
 [ 7443.5   7898.  ]
 [17925.12 17199.  ]
 [ 7057.9   6529.  ]
 [20542.4  20970.  ]
 [36240.4  31400.5 ]
 [13145.   10945.  ]
 [14743.6  18344.  ]
 [ 6380.7   8916.5 ]
 [16387.9   9989.  ]
 [12713.6   9295.  ]
 [19245.4  18920.  ]
 [ 8421.7   7895.  ]
 [ 6259.4   6488.  ]
 [ 9991.4   9959.  ]
 [13373.   15580.  ]
 [11075.6   9895.  ]
 [17309.9  11549.  ]
 [17545.5  15998.  ]
 [ 7081.3   5118.  ]
 [ 7278.5   6938.  ]
 [15655.   16695.  ]
 [ 7528.    8358.  ]
 [ 6929.    5499.  ]
 [ 8295.6   7975.  ]
 [11859.8  12290.  ]
 [15451.12 22018.  ]
 [10021.    8948.  ]
 [ 7188.6   6849.  ]
 [33779.8  41315.  ]
 [ 9799.9  11595.  ]
 [17406.2  18150.  ]
 [ 6147.7   6377.  ]
 [38114.8  45400.  ]
 [ 6345.4   8916.5 ]]


In [59]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.889499417689645

In [60]:
pd.read_csv('CarPrice_Assignment2.csv')

car_ID  symboling                   CarName fueltype aspiration  \
0         1          3        alfa-romero giulia      gas        std   
1         2          3       alfa-romero stelvio      gas        std   
2         3          1  alfa-romero Quadrifoglio      gas        std   
3         4          2               audi 100 ls      gas        std   
4         5          2                audi 100ls      gas        std   
..      ...        ...                       ...      ...        ...   
200     201         -1           volvo 145e (sw)      gas        std   
201     202         -1               volvo 144ea      gas      turbo   
202     203         -1               volvo 244dl      gas        std   
203     204         -1                 volvo 246   diesel      turbo   
204     205         -1               volvo 264gl      gas      turbo   

    doornumber      carbody drivewheel enginelocation  wheelbase  carlength  \
0          two  convertible        rwd          front       88.6      168.8   
1          two  convertible        rwd          front       88.6      168.8   
2          two    hatchback        rwd          front       94.5      171.2   
3         four        sedan        fwd          front       99.8      176.6   
4         four        sedan        4wd          front       99.4      176.6   
..         ...          ...        ...            ...        ...        ...   
200       four        sedan        rwd          front      109.1      188.8   
201       four        sedan        rwd          front      109.1      188.8   
202       four        sedan        rwd          front      109.1      188.8   
203       four        sedan        rwd          front      109.1      188.8   
204       four        sedan        rwd          front      109.1      188.8   

     carwidth  carheight  curbweight enginetype cylindernumber  enginesize  \
0        64.1       48.8        2548       dohc           four         130   
1        64.1       48.8        2548       dohc           four         130   
2        65.5       52.4        2823       ohcv            six         152   
3        66.2       54.3        2337        ohc           four         109   
4        66.4       54.3        2824        ohc           five         136   
..        ...        ...         ...        ...            ...         ...   
200      68.9       55.5        2952        ohc           four         141   
201      68.8       55.5        3049        ohc           four         141   
202      68.9       55.5        3012       ohcv            six         173   
203      68.9       55.5        3217        ohc            six         145   
204      68.9       55.5        3062        ohc           four         141   

    fuelsystem  boreratio  stroke  compressionratio  horsepower  peakrpm  \
0         mpfi       3.47    2.68               9.0         111     5000   
1         mpfi       3.47    2.68               9.0         111     5000   
2         mpfi       2.68    3.47               9.0         154     5000   
3         mpfi       3.19    3.40              10.0         102     5500   
4         mpfi       3.19    3.40               8.0         115     5500   
..         ...        ...     ...               ...         ...      ...   
200       mpfi       3.78    3.15               9.5         114     5400   
201       mpfi       3.78    3.15               8.7         160     5300   
202       mpfi       3.58    2.87               8.8         134     5500   
203        idi       3.01    3.40              23.0         106     4800   
204       mpfi       3.78    3.15               9.5         114     5400   

     citympg  highwaympg    price  
0         21          27  13495.0  
1         21          27  16500.0  
2         19          26  16500.0  
3         24          30  13950.0  
4         18          22  17450.0  
..       ...         ...      ...  
200       23          28  16845.0  
201       19          25  19045.0  
202       18     