In [1]:
import numpy


In [6]:
import numpy
op= list(map(int,input().split()))
op = numpy.asarray(op)
print(op)
"".join(map(str,op))

12 234 5
[ 12 234   5]


'122345'

# INDEXCING

In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])
print(arr[1]+arr[2])

1
5


In [9]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])    #array[row,colume]

2nd element on 1st row:  2


In [10]:
#Access the third element of the second array of the first array:

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


# slicing


In [11]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [13]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])        #2D SLICING

print(arr[1, 1:4])

[7 8 9]
