In [1]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
  z.append(i + j)
print(z)


[5, 7, 9, 11]


In [4]:
import numpy as np

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)

[ 5  7  9 11]


In [9]:
import numpy as np

def myadd(x, y):
  return x-y

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))


[-4 -4 -4 -4]


In [10]:
import numpy as np

print(type(np.add))

<class 'numpy.ufunc'>


In [11]:
.add()
.subtract()
.multiply()
.divide()
.power()
.mod() / .remainder()
.absolute(arr)



SyntaxError: invalid syntax (486688598.py, line 1)

In [12]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.divmod(arr1, arr2)

print(newarr)

(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


In [15]:
import numpy as np

arr = np.trunc([-3.1666, 3.6667])   #.fix()

print(arr)

[-3.  3.]


In [16]:
import numpy as np

arr = np.around(3.1666, 2)

print(arr)

3.17


In [17]:
import numpy as np

arr = np.floor([-3.1666, 3.6667])

print(arr)

[-4.  3.]


In [18]:
import numpy as np

arr = np.ceil([-3.1666, 3.6667])

print(arr)

[-3.  4.]


In [21]:
import numpy as np

arr = np.arange(1, 10)

print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


In [22]:
from math import log
import numpy as np

nplog = np.frompyfunc(log, 2, 1)

print(nplog(100, 15))

1.7005483074552052


In [23]:
import numpy as np

arr1 = np.array([1, 2, 3])    #s
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2])

print(newarr)

12


In [24]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis=1)

print(newarr)

[6 6]


In [25]:
import numpy as np

arr = np.array([1, 2, 3])
                             ###############one by one addition
newarr = np.cumsum(arr)

print(newarr)

[1 3 6]


In [27]:
import numpy as np

arr = np.array([1, 2, 3, 4])

x = np.prod(arr)

print(x)

24


In [28]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

x = np.prod([arr1, arr2])

print(x)
#1*2*3*4*5*6*7*8

40320


In [29]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

x = np.prod([arr1, arr2],axis=1)

print(x)


[  24 1680]


In [30]:
import numpy as np

arr = np.array([5, 6, 7, 8])
                                            ########one by one product
newarr = np.cumprod(arr)

print(newarr)

[   5   30  210 1680]


In [31]:
import numpy as np

arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr)

print(newarr)

[  5  10 -20]


In [32]:

arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr, n=2)#######n=2 will do the diffrence two times

print(newarr)

[  5 -30]


In [33]:
import numpy as np

num1 = 4
num2 = 6

x = np.lcm(num1, num2)

print(x)


12


In [40]:
import numpy as np

arr = np.array([3, 6, 9,10])

x = np.lcm.reduce(arr)

print(x)

1


In [41]:
import numpy as np

arr = np.arange(1, 11)

x = np.lcm.reduce(arr)

print(x)


2520


In [44]:
import numpy as np

num1 = 6
num2 = 9


x = np.gcd(num1, num2)

print(x)

3


In [45]:
import numpy as np

arr = np.array([3, 6, 9,10])

x = np.gcd.reduce(arr)

print(x)

1


In [46]:
import numpy as np

arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x = np.unique(arr)

print(x)

[1 2 3 4 5 6 7]


In [47]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.union1d(arr1, arr2)

print(newarr)

[1 2 3 4 5 6]


In [48]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.intersect1d(arr1, arr2)

print(newarr)

[3 4]


In [49]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.setdiff1d(arr1, arr2,assume_unique=True)

print(newarr)

[1 2]


In [50]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.setxor1d(arr1, arr2)

print(newarr)

[1 2 5 6]


In [61]:
from numpy import random

x = random.rand()

print(x)

0.17689169454039244


In [63]:
from numpy import random

x = random.rand(10)

print(x)

[0.06640532 0.67853102 0.09093459 0.33402427 0.77828005 0.08691215
 0.3450161  0.89019729 0.35080896 0.74774565]
